#!/usr/bin/expect

set timeout 2

spawn ./bla
send "abc\n"
send "123\n"
send "\x004"

# close
# wait
# # send -- \r

expect {
timeout { send_user "timeout"; exit 1 }
eof { send_user "eof"; exit 1 }
# "AAabc" { send_user "fff"; exit 0 }
}
