#!/bin/bash

RESPONSE+="PID: $$
"
RESPONSE+="$(set | grep "REQUEST_")
"
# RESPONSE+="$(set | grep SOCAT)
# "
RESPONSE+="1234567890"

echo_response_status_line
echo_response_default_headers
echo "Content-Type: text/plain; charset=utf-8"
echo "Content-Length: ${#RESPONSE}"
echo
echo "${RESPONSE}"

