#!/bin/bash

RESPONSE=""
RESPONSE+="Test
"

echo_response_status_line
echo_response_default_headers
echo "Content-Type: text/plain; charset=utf-8"
echo "Content-Length: ${#RESPONSE}"
echo
echo "${RESPONSE}"

